# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ru/team42/events/message_batch.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ru/team42/events/message_batch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ru/team42/events/message_batch.proto\x12\x10ru.team42.events\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x07\n\x11MessageBatchEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12/\n\x0boccurred_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07team_id\x18\x03 \x01(\t\x12/\n\x0b\x62\x61tch_start\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tbatch_end\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12@\n\x08messages\x18\x06 \x03(\x0b\x32..ru.team42.events.MessageBatchEvent.MessageDto\x12?\n\x04team\x18\x07 \x03(\x0b\x32\x31.ru.team42.events.MessageBatchEvent.TeamMemberDto\x12>\n\x07\x63olumns\x18\x08 \x03(\x0b\x32-.ru.team42.events.MessageBatchEvent.ColumnDto\x12@\n\x08stickers\x18\t \x03(\x0b\x32..ru.team42.events.MessageBatchEvent.StickerDef\x1a\x93\x01\n\nMessageDto\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nmessage_id\x18\x06 \x01(\t\x1ai\n\rTeamMemberDto\x12\x13\n\x0btelegram_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\t\x1a&\n\tColumnDto\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x1az\n\nStickerDef\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x43\n\x06states\x18\x04 \x03(\x0b\x32\x33.ru.team42.events.MessageBatchEvent.StickerStateDef\x1a,\n\x0fStickerStateDef\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\tB5\n\x1eru.team42.backend.proto.eventsB\x11MessageBatchProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ru.team42.events.message_batch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036ru.team42.backend.proto.eventsB\021MessageBatchProtoP\000'
  _globals['_MESSAGEBATCHEVENT']._serialized_start=92
  _globals['_MESSAGEBATCHEVENT']._serialized_end=1019
  _globals['_MESSAGEBATCHEVENT_MESSAGEDTO']._serialized_start=555
  _globals['_MESSAGEBATCHEVENT_MESSAGEDTO']._serialized_end=702
  _globals['_MESSAGEBATCHEVENT_TEAMMEMBERDTO']._serialized_start=704
  _globals['_MESSAGEBATCHEVENT_TEAMMEMBERDTO']._serialized_end=809
  _globals['_MESSAGEBATCHEVENT_COLUMNDTO']._serialized_start=811
  _globals['_MESSAGEBATCHEVENT_COLUMNDTO']._serialized_end=849
  _globals['_MESSAGEBATCHEVENT_STICKERDEF']._serialized_start=851
  _globals['_MESSAGEBATCHEVENT_STICKERDEF']._serialized_end=973
  _globals['_MESSAGEBATCHEVENT_STICKERSTATEDEF']._serialized_start=975
  _globals['_MESSAGEBATCHEVENT_STICKERSTATEDEF']._serialized_end=1019
# @@protoc_insertion_point(module_scope)
