management:
    tracing:
        sampling:
            probability: 0.0
    otlp:
        metrics:
            export:
                enabled: false

#logging:
#    level:
#        org.springframework.web.reactive.function.client: DEBUG
#        reactor.netty.http.client: DEBUG
#        org.springframework.security: DEBUG
